### PR TITLE
CHORE: unpretty-fy the UI of the app and upgrade libraries to latest

### PR DESCRIPTION
**Pull request by kappamax**

### CODE REVIEW

**Review by freakmode — COMMENTED** [review]
why did we decide to do this?

**Comment by kappamax** [comment]
+ The library upgrade was just something I've been meaning to do everytime I run the app - I don't like outdated libraries, or warnings in my startup logs.

+ The styling is only a suggestion based on @johnsylvain's feedback that there's currently very little to style in the current React homework, which I know was also previous feedback from @freakmode that we didn't leave anything for them to style. I think you guys can do a better job at unprettyfying the UI, but being artists in the craft it's probably hard for you guys to leave it looking unpolished.

**Comment by freakmode** [comment]
@kappamax 

We decided to add the styling to reduce overall time for the candidate. Folks were taking a lot of time with CSS and we didn't think that was the best use of their time for this exercise. I'm all for creativity and CSS chops, but by removing all of this we probably just added another hour to the assignment.

**Comment by kappamax** [comment]
@freakmode, should we make a brand new repo here and different assignment for the UI engineers since we need to see how they do on the styling aspect and some interaction as well?

**Pull request closed without merging**
